#Note: this file is necessary to build in ReadTheDocs
name: pycziutils
dependencies:
  - python>=3.5 
  - openjdk
  - pip
  - numpy # to solve python-javabridge installation error in read the doc build
  - pip:
    - -r file:requirements.txt
