# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
        os: [ubuntu-18.04, macos-latest, windows-latest]
        poetry-version: [1.1.2]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set up Java
      uses: AdoptOpenJDK/install-jdk@v1
#      uses: joschi/setup-jdk@v2
      with:
        version: '8' # The OpenJDK version to make available on the path
        architecture: 'x64' # defaults to 'x64'
        targets: 	JAVA_HOME
    - run : java --help
    # - run: java -cp java HelloWorldApp
    #  uses: actions/setup-java@v2
    #  with:
    #      distribution: 'zulu'
    #      java-version: '8'
    - name: Set up Poetry ${{ matrix.poetry-version }}
      uses: abatilo/actions-poetry@v2.0.0
      with:
          poetry-version: ${{ matrix.poetry-version }}
    - name: Install Dependencies
      run: |
        poetry update
        poetry install 
    - name: Test with pytest
      run: |
        make test
